### ISSUE TITLE
Unanable to run solc compliers

### ISSUE THREAD

**Issue by prabu2006it** [DigixGlobal/ethereum-ruby#15]
I am new to ethereum implementation

when i try to DO Solidity contract compilation and deployment process, I am getting the following error.Please do needful to fix this problem.

**SystemCallError: unknown error - Unanable to run solc compliers**
	from /home/haloprabu/.rvm/gems/ruby-2.4.0@blockchain/gems/ethereum.rb-2.0.8/lib/ethereum/solidity.rb:35:in `execute_solc'

Please do let me know what might be wroung.

**Comment by felipeands** [comment]
`brew install solidity` did the trick for me

**Comment by prabu2006it** [comment]
Thanks for your response.Will do the same and let you know if any issues.
